-
  branches:
    except:
      - master

  skip_tags: true

  configuration: Debug

  image: Visual Studio 2017

  build_script:
    - cmd: dotnet restore -v m  ./src/Telegraf.Clients.sln
    - cmd: dotnet build  -v m -c Debug ./src/Telegraf.Clients.sln
       
  artifacts:
    - path: "./packages/*.*"
-
  branches:
    only:
      - master

  configuration: Release

  image: Visual Studio 2017

  build_script:
    - cmd: dotnet restore -v m  ./src/Telegraf.Clients.sln
    - cmd: dotnet build  -v m -c Release ./src/Telegraf.Clients.sln
      
  artifacts:
    - path: "./packages/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: 642CQyNRZfe9fDFvEdV5ISN5ggxFvY82meXc2zwaj18sG96g4cR+sfi8xG/9enGC
      skip_symbols: false
      artifact: /.*\.nupkg/